if do_GWS
    fig = figure('Units','centimeters','Position',[10 10 15 15]);
    ha = tight_subplot(1,8,.1,.1); hold on; box on;
    
    subplot_x = 0.05;      subplot_y = 0.5;
    subplot_width = 0.225;   subplot_height = subplot_width;
    subplot_buffer = 0.01;
    
    axes(ha(1));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(1)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    ylabel('y, \lambda');
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(1)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(1)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(1),'Position',[subplot_x subplot_y subplot_height subplot_height],'YDir','reverse','XTick',[],...
        'ColorScale',color_scale);
    
    c = colorbar('Location','northoutside');
    c.Label.String = 'Normalised intensity';
    c.Label.FontName = 'cmss10';
    c.Label.FontSize = get(groot,'defaultAxesFontSize');
    % clim([0 1])
    set(c,'Position',[subplot_x subplot_y+subplot_height+subplot_buffer...
        3.1*subplot_height+4*subplot_buffer 0.1*subplot_height])
    
    axes(ha(2));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(2)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(2)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(2)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(2),'Position',[subplot_x+subplot_height+subplot_buffer subplot_y...
        subplot_height subplot_height],'YTick',[],'YDir','reverse','XTick',[],...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(3));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(3)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(3)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(3)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(3),'Position',[subplot_x+2*subplot_height+2*subplot_buffer subplot_y...
        subplot_height subplot_height],'YTick',[],'YDir','reverse','XTick',[],...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(4));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(4)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(4)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(4)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(4),'Position',[subplot_x+3*subplot_height+3*subplot_buffer subplot_y...
        subplot_height subplot_height],'YTick',[],'YDir','reverse','XTick',[],...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(5));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(5)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    xlabel('x, \lambda');   ylabel('y, \lambda');
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(5)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(5)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(5),'Position',[subplot_x subplot_y-subplot_height-subplot_buffer...
        subplot_height subplot_height],'YDir','reverse',...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(6));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(6)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    xlabel('x, \lambda'); 
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(6)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(6)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(6),'Position',[subplot_x+subplot_height+subplot_buffer subplot_y-subplot_height-subplot_buffer...
        subplot_height subplot_height],'YTick',[],'YDir','reverse',...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(7));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(7)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6)
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    xlabel('x, \lambda');
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(7)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(7)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(7),'Position',[subplot_x+2*subplot_height+2*subplot_buffer subplot_y-subplot_height-subplot_buffer...
        subplot_height subplot_height],'YTick',[],'YDir','reverse',...
        'ColorScale',color_scale);
    % clim([0 1])
    
    axes(ha(8));    hold on;    box on;
    [GWS_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
        z_sources,eigenvectors(:,idx_to_plot(8)),z_dipole_positions,show_pol_plots);
    imagesc(x_points/wavelength,x_points/wavelength,...
        (abs(GWS_field).^2)./max(abs(GWS_field(:,:)).^2));
    p1 = plot(real(z_dipole_positions)/(wavelength),...
        imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','.','MarkerSize',7,'Color',col6,...
        'DisplayName',['Dipoles (' num2str(n_dipoles) ')']);
    plot(real(moving_dipole_positions)/(wavelength),...
        imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
        'Marker','o','MarkerSize',7,'Color',col6)
    axis image
    xlabel('x, \lambda'); 
    text(-0.55*scale,-0.5*scale,['abs(\nu) = ' num2str(abs_eigvals(idx_to_plot(8)),3)],...
        'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    text(-0.55*scale,0.5*scale,num2str(idx_to_plot(8)),'Color','black','BackgroundColor',[1 1 1 0.5],...
        'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'));
    set(ha(8),'Position',[subplot_x+3*subplot_height+3*subplot_buffer subplot_y-subplot_height-subplot_buffer...
        subplot_height subplot_height],'YDir','reverse','YTick',[],...
        'ColorScale',color_scale);
    legend(p1,'Position',[subplot_x+3.5*subplot_width+4*subplot_buffer subplot_y+subplot_height+subplot_buffer ...
    0.1*subplot_width 0.1*subplot_height])
    % clim([0 1])

    set(ha(1),'YTick',get(ha(5),'XTick'))
    set(ha(5),'YTick',get(ha(5),'XTick'))
end