tic
% Generate some colors to use in fluctuation plots:
random_colors = rand(n_movements,1);    [~,~,random_color_idx] = unique(random_colors, 'stable');
colors = default_cmap(round(linspace(1,175,n_movements)),:);

[optimised_total_field,~] = DDA_true2D(k0,alpha,z_full_2d,exclusion_radius,...
    z_sources,optimised_field,z_dipole_positions,show_pol_plots);

%Calculate fluctuations of the initial and optimised fields:
fig = figure('Units','centimeters','Position',[10 10 15 15]);
ha = tight_subplot(1,4,.1,.15,.15);

subplot_x = 0.05;      subplot_y = 0.15;
subplot_width = 0.3;   subplot_height = subplot_width;
subplot_buffer = 0.025;

axes(ha(1));    hold on;    box on;
imagesc(x_points./wavelength,x_points./wavelength,...
    (abs(initial_total_field).^2)...
    ./max(max(abs(initial_total_field(:,end)).^2)));
plot(real(z_dipole_positions)/(wavelength),...
    imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
    'Marker','.','MarkerSize',10,'Color',col6)
plot(real(moving_dipole_positions)/(wavelength),...
    imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
    'Marker','o','MarkerSize',10,'Color',col6)
set(ha(1),'Position',[subplot_x subplot_y subplot_width subplot_height],...
    'Color', 'w','YDir','reverse','ColorScale',color_scale);
axis image;     xlabel('x, \lambda');   ylabel('y, \lambda');
% clim([0 1]);
title('Plane wave','FontName','cmss10','FontSize',1.1*get(groot,'defaultAxesFontSize'),...
    'FontWeight','normal');
  
axes(ha(2));    hold on;    box on;
field_fluctuations = testDipoleMovement(source_field,n_movements,movement_stdev,...
    k0,alpha,z_full_2d,static_dipole_positions,moving_dipole_positions,...
    z_sources,z_detectors);
for n = 1:size(field_fluctuations,2)
    plot((abs(field_fluctuations(:,n)).^2)./max(max(abs(field_fluctuations).^2)),...
        y_detectors,'Color',colors(random_color_idx(n),:));
end
set(ha(2),'Position',[subplot_x+subplot_width+0.5*subplot_buffer subplot_y ...
    0.4*subplot_width subplot_height],...
    'YDir','reverse','XAxisLocation','top','YTick',[]);
text(0.1,-0.5*scale,['\xi = ' num2str(mean(std(abs(field_fluctuations),0,2))...
    /mean(mean(abs(field_fluctuations).^2,1)),'%.2f')],...
    'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'),...
    'BackgroundColor',[1 1 1 0.5],'EdgeColor','black');
axis([0 1 x_start -x_start])

axes(ha(3));    hold on;    box on;
imagesc(x_points./wavelength,x_points./wavelength,...
    (abs(optimised_total_field).^2)...
    ./max(max(abs(optimised_total_field(:,end)).^2)));
p1 = plot(real(z_dipole_positions)/(wavelength),...
    imag(z_dipole_positions)/(wavelength),'LineStyle','none',...
    'Marker','.','MarkerSize',10,'Color',col6,...
    'DisplayName',['Dipoles (' num2str(n_dipoles) ')']);
plot(real(moving_dipole_positions)/(wavelength),...
    imag(moving_dipole_positions)/(wavelength),'LineStyle','none',...
    'Marker','o','MarkerSize',10,'Color',col6)
% clim([0 1]);
axis image;     xlabel('x, \lambda');   
set(ha(3),'Position',[subplot_x+1.4*subplot_width+2*subplot_buffer...
    subplot_y subplot_width subplot_height],...
    'Color', 'w','YDir','reverse','ColorScale',color_scale);
title('Optimised wave','FontName','cmss10','FontSize',1.1*get(groot,'defaultAxesFontSize'),...
    'FontWeight','normal');
legend(p1,'Position',[subplot_x+2.4*subplot_width+3.25*subplot_buffer subplot_y+subplot_height+1.75*subplot_buffer ...
    0.1*subplot_width 0.1*subplot_height])
  
axes(ha(4));    hold on;    box on;
field_fluctuations = testDipoleMovement(optimised_field,n_movements,movement_stdev,...
    k0,alpha,z_full_2d,static_dipole_positions,moving_dipole_positions,...
    z_sources,z_detectors);
for n = 1:size(field_fluctuations,2)
    plot((abs(field_fluctuations(:,n)).^2)./max(max(abs(field_fluctuations).^2)),...
        y_detectors,'Color',colors(random_color_idx(n),:));
end
set(ha(4),'Position',[subplot_x+2.4*subplot_width+2.5*subplot_buffer subplot_y ...
    0.4*subplot_width subplot_height],...
    'YDir','reverse','XAxisLocation','top','YTick',[]);
text(0.1,-0.5*scale,['\xi = ' num2str(mean(std(abs(field_fluctuations),0,2))...
    /mean(mean(abs(field_fluctuations).^2,1)),'%.2f')],...
    'FontName','cmss10','FontSize',get(groot,'defaultAxesFontSize'),...
    'BackgroundColor',[1 1 1 0.5],'EdgeColor','black');
axis([0 1 x_start -x_start])

c = colorbar('northoutside');       c.Label.String = 'Normalised intensity';   
c.Label.FontSize = get(groot,'defaultaxesfontsize');
c.Label.FontName = 'cmss10';
set(c,'Position',[subplot_x subplot_y+subplot_height+1.75*subplot_buffer ...
    2.25*subplot_width+1.5*subplot_buffer 0.075*subplot_height])


disp(['Plotting fast optimiser v2 results took ' num2str(toc) ' seconds.'])